version: 2

updates:
  # Api
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "monthly"

  # Client
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "monthly"
