version: 2

updates:
  # Api
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "saturday"

  # Client
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "saturday"
