version: "3.8"

services:
  proxy:
    image: haproxy:2.3-alpine
    restart: unless-stopped
    links:
      - api
      - client
    ports:
      - 80:80
    volumes:
      - ./docker/proxy:/usr/local/etc/haproxy:ro
    environment:
      - DOMAIN=${DOMAIN}
      - CLIENT_PORT=${CLIENT_PORT}
      - API_PORT=${API_PORT}

  client:
    image: ghcr.io/kostaspt/domane-client:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - CLIENT_PORT=${CLIENT_PORT}

  api:
    image: ghcr.io/kostaspt/domane-api:latest
    restart: unless-stopped
    environment:
      - API_PORT=${API_PORT}
