name: Api
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/api.yml
      - api/**

defaults:
  run:
    working-directory: api

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15"

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/vendor"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/go.sum') }}

      - name: Download packages
        run: make deps

      - name: Run tests
        run: make test

  deploy:
    name: Deploy
    needs: test
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_LOGIN_TOKEN }}

      - name: Build Docker Image
        run: docker build -t docker.pkg.github.com/kostaspt/domane/domane-api:latest .

      - name: Push to Registry
        run: docker push docker.pkg.github.com/kostaspt/domane/domane-api:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOMANE_SSH_HOST }}
          username: ${{ secrets.DOMANE_SSH_USER }}
          passphrase: ${{ secrets.DOMANE_SSH_PASSPHRASE }}
          key: ${{ secrets.DOMANE_SSH_PRIVATE_KEY}}
          script: cd /app && docker-compose pull api && docker-compose up -d --force-recreate api;
