name: Api
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/api.yml
      - api/**
  pull_request:
    paths:
      - .github/workflows/api.yml
      - api/**

defaults:
  run:
    working-directory: api

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/cache@v2
        with:
          path: "**/vendor"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/go.sum') }}

      - name: Download packages
        run: make deps

      - name: Format
        run: make format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "fix(api): code format"
          branch: ${{ github.head_ref }}

      - name: Run tests
        run: make test

  deploy:
    name: Deploy
    needs: test
    timeout-minutes: 10

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_LOGIN_TOKEN }}

      - name: Build Docker Image
        run: docker build --build-arg DOMAIN=domane.io -t ghcr.io/kostaspt/domane-api:latest .

      - name: Push to Registry
        run: docker push ghcr.io/kostaspt/domane-api:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOMANE_SSH_HOST }}
          username: ${{ secrets.DOMANE_SSH_USER }}
          passphrase: ${{ secrets.DOMANE_SSH_PASSPHRASE }}
          key: ${{ secrets.DOMANE_SSH_PRIVATE_KEY}}
          script: cd /app && docker-compose pull api && docker-compose up -d --force-recreate api;
